name: Dependency Graph Submission

on:
  push:
    branches:
      - main

jobs:
  submit-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Component detection and dependency submission
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
