name: Build and Submit Dependencies

permissions:
  contents: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VCPKG_FEATURE_FLAGS: dependencygraph
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SFML system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxi-dev libxrandr-dev libxcursor-dev libudev-dev libgl1-mesa-dev

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies with vcpkg
        run: ./vcpkg/vcpkg install

      - name: Configure project with CMake (vcpkg toolchain)
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build project
        run: cmake --build build
        
